### PR TITLE
Add a call to action to visit

### PR DESCRIPTION
**Pull request by JLDohm**
Includes open hours and a link to tell us you're coming
Addresses Issue #35

### CODE REVIEW

**Comment by artlogic** [comment]
@JLDohm Thank you for submitting this! I gave it a try on my system and it looks like this:

Screenshot from 2020-02-25 15-53-33

Given your text formatting, I'm wondering if you meant to break it up into many lines?

**Comment by JLDohm** [comment]
I did want multiple lines. Is there a way to preview things without
installing Jekyll on my computer? Getting that up and running is probably
at the edge of my abilities.

**Comment by artlogic** [comment]
> I did want multiple lines. Is there a way to preview things without installing Jekyll on my computer? Getting that up and running is probably at the edge of my abilities.

Absolutely! When you made your edit a fork was made on your account: https://github.com/JLDohm/site - your changes ended up on a branch called patch-1: https://github.com/JLDohm/site/tree/patch-1

If instead you make your changes on the master branch of your copy of the site then github will publish the changes for you: https://github.com/JLDohm/site/tree/master

Once you've made your changes to master, you need to go into settings and tell github pages to publish the master branch. Then you can view a preview of your changes.

If you'd like help, I'm happy to meet with you at the space!

**Comment by artlogic** [comment]
@JLDohm I hope you don't mind, but given the current situation I'm going to close this for now.

**Pull request closed without merging**
