### PR TITLE
Add  reservations form

### PR DESCRIPTION
**Pull request by JLDohm**
also navigation

### CODE REVIEW

**Comment by artlogic** [comment]
@JLDohm I don't think this should be in the top nav. I think the site should mostly be a resource for non-members with members resources mostly being on the wiki. Given the extraordinary circumstances, I do think this belongs on the site - however, I think it should just be linked from our various messages informing people that the space is open for members only at the moment.

**Comment by JLDohm** [comment]
I can't figure out how to remove the commit.

**Comment by JLDohm** [comment]
I can't figure out how to remove the commit. Can someone help?

**Comment by artlogic** [comment]
Don't worry about removing it. Just put the file back to the way it was and commit again.

(There is a way, but I'm assuming you aren't looking to learn git)

**Comment by JLDohm** [comment]
Updated, @artlogic please review

**Comment by artlogic** [comment]
@JLDohm I think we're close here, but we need links from the COVID messages on the site to this reservation form.

**Comment by JLDohm** [comment]
Ready for review again

**Pull request merged**
